libqpdf/QUtil.cc: fix build without wchar
Build on Linux toolchains without wchar fails since version 9.1.1 and
a44b5a34a07b9f2905d419d5571fd53832c1f6c0 on:

libqpdf/QUtil.cc: In function 'int QUtil::call_main_from_wmain(int, wchar_t**, std::function<int(int, char**)>)':
libqpdf/QUtil.cc:2378:32: error: 'wcslen' was not declared in this scope
         for (size_t j = 0; j < wcslen(argv[i]); ++j)
                                ^~~~~~

To fix this error, return -1 if WINDOWS_WMAIN is not defined

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>